### ISSUE TITLE
linux 1.4.0版本存在报错

### ISSUE THREAD

**Issue by aaqiqi1** [smallfox233/JsonExp#10]
<img width="695" alt="image" src="https://github.com/smallfox233/JsonExp/assets/62644818/ed580406-ecc9-479d-81aa-2e6f237e9971">

安装了相关组件也是存在报错
<img width="739" alt="image" src="https://github.com/smallfox233/JsonExp/assets/62644818/8d411e99-c315-4b68-819c-8c509c5acd14">

**Comment by smallfox233** [comment]
最近有些忙，可能过段时间后再去看看了

**Comment by smallfox233** [comment]
> <img alt="image" width="695" src="https://private-user-images.githubusercontent.com/62644818/284164373-ed580406-ecc9-479d-81aa-2e6f237e9971.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2Mzc0NTcsIm5iZiI6MTcyMTYzNzE1NywicGF0aCI6Ii82MjY0NDgxOC8yODQxNjQzNzMtZWQ1ODA0MDYtZWNjOS00NzlkLTgxYWEtMmU2ZjIzN2U5OTcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDA4MzIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5MTU0NjZmN2Q4MDJmOTJhM2U3MTY1MGZmNWE3NDcyZWRiNDQwZTUzZDc2ZTJlMzExZWYzYWNhNzE5YzM4MzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c64e--7iZ7Fsf1jMSH-fjPBpHaWNP_FYVrR2AZTFU2k">
> 安装了相关组件也是存在报错 <img alt="image" width="739" src="https://private-user-images.githubusercontent.com/62644818/284165470-8d411e99-c315-4b68-819c-8c509c5acd14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2Mzc0NTcsIm5iZiI6MTcyMTYzNzE1NywicGF0aCI6Ii82MjY0NDgxOC8yODQxNjU0NzAtOGQ0MTFlOTktYzMxNS00YjY4LTgxOWMtOGM1MDljNWFjZDE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDA4MzIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1OTExYzRkMTU2ZGZkNDViYTNhOGIzNjk3NTBiZWNhZjBjNDg5NzMzNzhiM2NkM2U3NDk0MDIxZGQ2ZTllMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AcTJsRnZFzqXmAuB6urCMVa2ETCin3AEM8PJmhrygsk">

1.4.1版本已开源，可以使用python3调用
