### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by xiaotchehehe** [smallfox233/JsonExp#13]
大佬你好，实战中，-r -l参数无意义，直接自定义设置一个参数 -x rmi://xxx.xxx.xxx.xxx/xxxxxx 或者-x ldap://xxx.xxx.xxx.xxx/xxxxxx地址放进去就可以了 另外 能否加个自定义dnslog功能

**Comment by smallfox233** [comment]
前一个问题应该不影响使用，改成rmi://xxx/xx容易出现更多数据处理的bug；
第二个问题不知道你提到的dnslog是指的--dnslog参数还是什么，如果只是指定dnslog地址，-r和-l参数已经包含了这个功能。

**Comment by xiaotchehehe** [comment]
啊没注意哈哈哈我看看
