### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by charis3306** [smallfox233/JsonExp#2]
写个爬虫或使用长亭RAD 添加一些过滤规则
如何检测ldap rmi dns ftp mysql等，可以使用revsuit项目搭建的反链平台调用api。 具体可以看我https://github.com/charis3306/expStorm.git 项目XXL-JOB 实现原理。
项目链接如下：https://github.com/Li4n0/revsuit.git

**Comment by smallfox233** [comment]
感谢反馈，现在阶段比较忙，之后有时间会去看看

**Comment by smallfox233** [comment]
大概看了一下，你的意思是增加内置的反连平台吗，感觉有点偏离之前开发这个工具的意图；
目前只希望它能够精简些，使用者可以自己搭建反连平台，并通过参数来指定；

**Comment by smallfox233** [comment]
不太明白“增加过滤规则”的意思，是指绕waf还是什么

**Comment by charis3306** [comment]
能类似xray一样，在扫描的过程遇到漏洞直接展示出来，而不是到反链平台查看。不是增加内置的反连平台而使用revsuit项目作为反链平台。只需要使用者自己搭建的平台配置的token调用反链平台获取数据，代码进行校验同步展示漏洞就好。希望实现主动扫描，建议调用长亭RAD 和AWVS爬虫。获取的链接地址后通过过滤规则滤一些静态文件，如图片。然后扫描。

**Comment by smallfox233** [comment]
xray的fastjson漏洞也需要到反连平台才能查看的，在config.yaml中设置dnslog的地址，和工具的指定ldap、rmi地址是一样的效果

**Comment by smallfox233** [comment]
主动扫描去爆破路径的话，应该不会增加这个功能；之前弄这个工具是想弄漏洞利用工具，不是漏扫工具。各种的发包很容易就被封IP。

**Comment by smallfox233** [comment]
目前工具有点类似sqlmap，如果发现Content-Type的值为application/json（或是请求URL或body中含有json信息）就可以将请求包复制下来，进行检测和验证

**Comment by smallfox233** [comment]
v1.4版本新增了申请dnslog的功能，需要挂代理，会影响发包速度，勉强能用用
