### ISSUE TITLE
使用文件扫描 报错

### ISSUE THREAD

**Issue by cqrlhz** [smallfox233/JsonExp#3]
![捕获](https://user-images.githubusercontent.com/63200706/230848524-e32d4f1d-58f9-4787-8dc3-943061e0e707.PNG)

**Comment by smallfox233** [comment]
可以截图数据包内容吗，看下是哪个地方导致的问题

**Comment by smallfox233** [comment]
去排查了一下，有可能是在导入URL的时候复写了
请求中的host是test.com，报错显示的时候URL变成了http://test.com:test.com/路径
目前还没时间去改bug，后面有空的时候再弄下

**Comment by smallfox233** [comment]
修复了几个地方报错的问题，你可以下载v1.3.4版本再尝试一下，看看还有没有报错
https://github.com/smallfox233/JsonExp/releases/tag/v1.3.4
