### ISSUE TITLE
求mac版本

### ISSUE THREAD

**Issue by Cl-arctos** [smallfox233/JsonExp#4]
求mac版本

**Comment by smallfox233** [comment]
没mac电脑来打包程序

**Comment by smallfox233** [comment]
更新了v1.3.6版本，可以去试下

**Comment by Cl-arctos** [comment]
好哒，感谢大佬



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月25日(星期二) 中午11:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [smallfox233/JsonExp] 求mac版本 (Issue #4)





 
更新了v1.3.6版本，可以去试下
