### ISSUE TITLE
err

### ISSUE THREAD

**Issue by sdfdfasd12** [smallfox233/JsonExp#8]
![image](https://github.com/smallfox233/JsonExp/assets/144324900/0b40e74b-37e3-44df-895a-42df310ff449)

**Comment by smallfox233** [comment]
可以发一下版本么，我回头看下是什么问题导致的

**Comment by smallfox233** [comment]
> ![image](https://private-user-images.githubusercontent.com/144324900/269629129-0b40e74b-37e3-44df-895a-42df310ff449.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2Mzc0OTcsIm5iZiI6MTcyMTYzNzE5NywicGF0aCI6Ii8xNDQzMjQ5MDAvMjY5NjI5MTI5LTBiNDBlNzRiLTM3ZTMtNDRkZi04OTVhLTQyZGYzMTBmZjQ0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMlQwODMzMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YWE0ZmUxYTY5N2FiMTY2NjI2NGRhYzU5ZWE4MDZmOWU2NzFmN2NkNjUyN2FiOWM1MWMyN2E3ZjhlNzY2NDZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RNcH-vBWmcwaIKJHnIAFGdGjsHbW0YRsiFqSC1rDkuk)

1.4.1版本已开源，可使用python3去调用
