### ISSUE TITLE
mac版本不兼容

### ISSUE THREAD

**Issue by Admin123456-check** [smallfox233/JsonExp#9]
<img width="473" alt="image" src="https://github.com/smallfox233/JsonExp/assets/50415778/58de4afe-7b2e-4224-9c0f-810c1923761b">

不支持inter版本的mac

**Comment by smallfox233** [comment]
我这边没inter的mac环境，打包不了

**Comment by NuOne1** [comment]
源码可以开源吗，可自行编译

**Comment by smallfox233** [comment]
> 源码可以开源吗，可自行编译

1.4.1版本已经开源了，可以直接用python3调用
